name: deeprl_udacity
channels:
  - default
dependencies:
  - python=3.7.3
  - black
  - matplotlib
  - numpy
  - jupyter
  - docopt
  - pyyaml
  - pandas
  - scipy
  - ipykernel
  - pip
  - pip:
      - torch==0.4.1
      - Pillow>=4.2.1
      - protobuf==3.6.1
      - grpcio==1.24.3
